### ISSUE TITLE
question with educational reason

### ISSUE THREAD

**Issue by DarthMoulByte** [Radivarig/UvSquares#12]
What do you mean exactly with this and how does it work? I do not understand the concept very well
**"Please disable 'Keep UV and edit mesh in sync'"**
```
def main(context, operator, square = False, snapToClosest = False):
    if context.scene.tool_settings.use_uv_select_sync:
        operator.report({'ERROR'}, "Please disable 'Keep UV and edit mesh in sync'")
        # context.scene.tool_settings.use_uv_select_sync = False
        return
```

**Comment by Radivarig** [comment]
This option syncs selection between UV Editor and 3D Viewport, adding some behavior that breaks the addon. When selecting vertices from UV Editor it will force select all vertices that share the same 3D Viewport location and when selecting faces from UV Editor it will only select those face vertices instead of all vertices that share the same 3D Viewport location contained in the surounding faces that touch.

There's a button in UV Editor panel that toggles this option.
