### ISSUE TITLE
Some shortcuts are changed

### ISSUE THREAD

**Issue by Radivarig** [Radivarig/UvSquares#42]
As mentioned here:
https://blenderartists.org/t/addon-uvsquares-v1-9-updated-2-80-and-multi-island-support/613111/130

**Comment by SevAm74** [comment]
Overriding the Alt-V shortcut to replace the V shortcut that was consistent with the V functionality in the 3D View while eliminating the Alt-V for Stitching functionality does not make sense to me. Please keep V consistent with mesh editing.
Alt-V is listed as the shortcut for Stitch in the UV menu of the UV Editor. I was about to report a bug to the blender tracker because Alt-V for stitching was broken but then I noticed it's this plugin.

If I press V to join like written in the UV Squares tab of the sidebar, it tells me rip failed. 

Please restore vanilla blender shortcuts.

**Comment by Radivarig** [comment]
Done

**Comment by Radivarig** [comment]
Fixed in 1.15.0
