### ISSUE TITLE
UvSquares_v1.14.2.zip won't install with Blender 3.6

### ISSUE THREAD

**Issue by 4E71-NOP** [Radivarig/UvSquares#58]
Hi,

Just to let you know.

UvSquares_v1.14.2.zip won't install with Blender 3.6.

Enabling the module gives the following error.

_File "whereItIsSupposedToBe\addon_utils.py", line 333, in enable mod = __import__(module_name)
ModuleNotFoundError: No module named 'UvSquares-master'_

Regards.

**Comment by ericwomer** [comment]
Change the folder name from UvSquares-master to UvSquares

**Comment by ericwomer** [comment]
Sorry, the problem is when you download the zip archive from github through the code button(?) it ends up creating a zip archive where everything is under the . or current directory, blender needs those to be either a single file or if its multiple files under its own root dir with a __init__.py file aka.


With the addon folder under the root users addons dir by the name of UvSquares
```
path/to/blender/3.6/scripts/addons/UvSquares/uv_squares.py
                                       |-->/__init__.py
                                       |-->/README
                                       |-->/LICENSE
```

or in the root of the users addons folder
```
path/to/blender/3.6/scripts/addons/uv_squares.py
```

The last layout doesn't work with some addons with multiple modules, it will work with this one since all of the module is in the one file, either place the __init__.py and uv_squares.py files under a folder together or delete __init__.py and keep the uv_squares.py under your users addons folder.

**Comment by Radivarig** [comment]
Yep
